# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHTa8E3DFBUe9295oTuw3Ys83TNxjGl5

***ZOMATA DATA ANALYSIS PROJECT***

**QUESTIONS:-**
*Ques- what type of resturant do the majority of customers order from?*

*Ques- how many votes has each type of resturant received from customers?*

*Ques- what are the ratings that the majority of resturants have received*

*Ques- zomato has observed that most couples order most of their food online. what is their avg spending on each order?*

*Ques- which mode(online/offline) has received the max rating?*

*Ques- which type of resturant received more offline orders, so that zomato can prefer customers with some good offers*

**STEP 1- IMPORTING LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**CREATE DATAFRAME**"""

dataframe = pd.read_csv("/content/Zomato data .csv")

dataframe

"""**CONVERT THE DATATYPE OF COLUMN-RATE**"""

def handlerate(value):
  value= str(value).split('/')
  value= value[0];
  return float(value)

dataframe['rate']=dataframe['rate'].apply(handlerate)
print(dataframe.head())

dataframe.info()

"""**TYPE OF RESTURANT**"""

dataframe.head()

dataframe.tail()

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel('Type of Restaurant')

"""*CONCLUSION - MAJORITY OF THE RESTURANT FALLS IN DINING CATEGORY*"""

dataframe.head()

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c="blue", marker="o")
plt.xlabel("TYPES OF RESTURANT", c="brown" , size=20)
plt.ylabel("VOTES", c="brown" , size=20)

"""*CONCLUSION - DINING RESTURANT HAS RECEIVED MAX VOTES*"""

dataframe.head()

plt.hist(dataframe['rate'],bins=5)
plt.title("ratings distribution")
plt.show()

"""*CONCLUSION - MAJORITY RESTURANTS RECEIVED RATINGS FROM 3.5 TO 4*

**AVERAGE ORDER SPENDING BY COUPLES**
"""

dataframe.head()

couple_data = dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""*CONCLUSION-  THE MAJORITY OF COUPLES PREFERRED COST OF 300 RS*

**WHICH MODE RECEIVED MAXIMUM RATING(ONLINE/OFFLINE)**
"""

dataframe.head()

plt.figure(figsize = (6,6))
sns.boxplot(x= 'online_order', y ='rate' , data = dataframe)

"""*CONCLUSION - OFFLINE ORDER RECEIVED LOWER RATING IN COPARISON TO ONLINE ORDER*"""

dataframe.head()

pivot_table = dataframe.pivot_table(index= 'listed_in(type)', columns = 'online_order', aggfunc= 'size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap= "YlGnBu", fmt='d')
plt.title("HEATMAP")
plt.xlabel("ONLINE ORDER")
plt.ylabel("LISTED IN(type)")
plt.show()

"""*CONCLUSION - DINING RESTURANTS PRIMARILY ACCEPT OFFLINE ORDERS, WHEREAS CAFES PRIMARILY RECEIVE ONLINE ORDERS. THIS SUGGESTS THAT CLIENTS PREFERS TO PLACE  ORDERS IN PERSON AT RESTURANTS, BUT PREFER ONLINE ORDERING AT CAFES.*"""